development:
  adapter: postgresql
  encoding: unicode
  database: instatalk_dev
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: instatalk_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: instatalk
  pool: 5
  username:
  password:
